# Generated by Django 4.2.16 on 2024-09-12 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('appointment_address', models.CharField(max_length=500)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('appointment_notes', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(max_length=100)),
                ('media_url', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('hashedPassword', models.CharField(max_length=200)),
                ('photo_url', models.CharField(max_length=500, null=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bio', models.CharField(max_length=500)),
                ('rating', models.IntegerField(null=True)),
                ('certified', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comments', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appointment')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('breed', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('age', models.IntegerField()),
                ('companion_notes', models.CharField(max_length=500, null=True)),
                ('pet_address', models.CharField(max_length=500)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.owner')),
                ('walkers', models.ManyToManyField(related_name='companions', to='main.walker')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='companion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.companion'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='walker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.walker'),
        ),
    ]
