# Generated by Django 4.2.16 on 2024-09-13 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_owner_user_alter_review_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('hashedPassword', models.CharField(max_length=200)),
                ('photo_url', models.CharField(max_length=500, null=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AlterField(
            model_name='walker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
